### ISSUE TITLE
Split Error

### ISSUE THREAD

**Issue by mushtash** [subasraj/flashpost-support#61]
Im trying to use postman collection in vscode flashpost extension
Environment is set
When i'm trying post to submit a file by selecting body i get the following error
Collection works well in Postman 
Can you assist to troubleshoot the issue

![Screenshot 2024-10-07 214040](https://github.com/user-attachments/assets/777b876d-9241-4d4e-a5d4-e8ef19647df8)

Name : TypeError

 Message : e.split is not a function

 Stack : TypeError: e.split is not a function
    at t.GetFileName (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3793111)
    at b (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3781084)
    at v (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3781864)
    at y (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3783834)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784635
    at Array.map (<anonymous>)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admn/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784623
    at t.Table (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3784644)
    at ii (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3495366)
    at qs (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/admin/.vscode/extensions/vasubasraj.flashpost-1.1.84/dist/flashpost-ui.js:204:3547491)

**Comment by subasraj** [comment]
update to the latest version and try again
